/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Выдать CSRF-куку перед формой входа.
         *
         *     Фронтенд — статика, отданная прокси, шаблонов Django он не рендерит,
         *     поэтому получить токен из скрытого поля формы неоткуда.
         */
        get: operations["api_auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/materials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Материалы в отгрузках
         * @description Сколько сырья ушло вместе с проданной продукцией. Проданное разворачивается по техкартам до того, что закупают.
         */
        get: operations["shipment_materials_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/materials/{material_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Материал в отгрузках — откуда взялось число
         * @description Из каких изделий материал пришёл и какими путями по техкартам. Фильтры те же, что у таблицы: слагаемые обязаны сходиться с числом своей строки.
         */
        get: operations["shipment_material_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/materials/xlsx/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Материалы в отгрузках — выгрузка в Excel
         * @description Та же выборка, что на экране, целиком. Вторым листом — проданное без техкарты: в сумму сырья оно не входит.
         */
        get: operations["shipment_materials_xlsx"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Товары в отгрузках
         * @description Что и сколько продано за период, свёрнутое по товару.
         */
        get: operations["shipment_products_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/products/{product_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Товар в отгрузках — детали строки
         * @description Разбивка по каналам, последние отгрузки и остаток. Фильтры те же, что у таблицы: детали обязаны сходиться с числами своей строки.
         */
        get: operations["shipment_product_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/products/xlsx/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Товары в отгрузках — выгрузка в Excel
         * @description Та же выборка, что на экране, но целиком: все страницы, а не видимая.
         */
        get: operations["shipment_products_xlsx"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обновить данные из МойСклада
         * @description Единственное место, где запрос человека доходит до МойСклада. Ограничено паузой между запусками и блокировкой: корзина лимита общая с ботом, который проверяет учёт круглосуточно.
         */
        post: operations["sync_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Идёт ли синхронизация
         * @description Состояние живёт на сервере, а не в памяти вкладки: иначе перезагрузка стирает его у запустившего, а остальные не видят вовсе.
         */
        get: operations["sync_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Доля канала в продажах товара. Основа полос в раскрытии строки. */
        ChannelShare: {
            id: number | null;
            name: string;
            /** Format: decimal */
            quantity: string;
            revenue_kopecks: number;
        };
        Csrf: {
            csrfToken: string;
        };
        Detail: {
            detail: string;
        };
        Health: {
            status: string;
            database: string;
        };
        Login: {
            username: string;
            password: string;
        };
        MaterialHead: {
            id: number;
            name: string;
            article: string;
            code: string;
            uom: string;
        };
        /**
         * @description Один путь по техкартам и то, сколько материала пришло именно им.
         *
         *     Количество обязательно: без него путь говорит «через замес и через
         *     розлив», но не отвечает, чего сколько, — а объяснение, которое не
         *     складывается обратно в объясняемое число, объяснением не является.
         */
        MaterialPath: {
            chain: string[];
            /** Format: decimal */
            quantity: string;
        };
        /**
         * @description Откуда взялась цена: документ, дата, поставщик.
         *
         *     Число, посчитанное по цене, обязано назвать её источник. Иначе колонка
         *     «Стоимость» остаётся суммой, за которую никто не отвечает.
         */
        MaterialPrice: {
            /** Format: decimal */
            price_kopecks: string;
            /** Format: date-time */
            moment: string;
            document_number: string;
            supplier: string;
        };
        /**
         * @description Свёрнутый хвост списка источников.
         *
         *     Без него показанные слагаемые не складывались бы в число, которое панель
         *     объясняет: у воды пятьдесят девять изделий-источников, а видно двадцать.
         */
        MaterialRest: {
            products_count: number;
            /** Format: decimal */
            quantity: string;
        };
        /** @description Изделие, из-за продажи которого материал израсходован. */
        MaterialSource: {
            product_id: number;
            name: string;
            /** Format: decimal */
            sold_quantity: string;
            sold_uom: string;
            /** Format: decimal */
            quantity: string;
            paths: components["schemas"]["MaterialPath"][];
        };
        /** @description Страница в меню. Префиксы API наружу не отдаются — это деталь защиты. */
        Page: {
            key: string;
            label: string;
            group: string;
            route: string;
        };
        ProductDocument: {
            number: string;
            /** Format: date-time */
            moment: string;
            agent: string;
            /** Format: decimal */
            quantity: string;
            total_kopecks: number;
        };
        Profile: {
            id: number;
            username: string;
            full_name: string;
            is_superuser: boolean;
            pages: components["schemas"]["Page"][];
        };
        Refused: {
            detail: string;
            retry_after_seconds: number;
        };
        SalesChannel: {
            id: number;
            name: string;
        };
        ShipmentMaterialDetail: {
            material: components["schemas"]["MaterialHead"];
            /** Format: decimal */
            quantity: string;
            cost_kopecks: number | null;
            price: components["schemas"]["MaterialPrice"] | null;
            stock: components["schemas"]["Stock"] | null;
            sources_count: number;
            sources: components["schemas"]["MaterialSource"][];
            rest: components["schemas"]["MaterialRest"] | null;
        };
        ShipmentMaterialRow: {
            material_id: number;
            name: string;
            article: string;
            code: string;
            uom: string;
            /** Format: decimal */
            quantity: string;
            products_count: number;
            /** Format: decimal */
            price_kopecks: string | null;
            /** Format: date-time */
            price_moment: string | null;
            cost_kopecks: number | null;
            /** Format: decimal */
            cost_share: string | null;
        };
        ShipmentMaterials: {
            /** Format: date-time */
            synced_at: string | null;
            count: number;
            totals: components["schemas"]["ShipmentMaterialsTotals"];
            coverage: components["schemas"]["ShipmentMaterialsCoverage"];
            results: components["schemas"]["ShipmentMaterialRow"][];
            without_plan: components["schemas"]["WithoutPlanRow"][];
            channels: components["schemas"]["SalesChannel"][];
        };
        /**
         * @description Насколько полное число видит человек — про выборку отгрузок целиком.
         *
         *     Поиск сюда не входит намеренно: он сужает список материалов, а не то,
         *     что отгрузили. Возьми стоимость с учётом поиска, а выручку без —
         *     получится дробь, которая выглядит обычным процентом и врёт молча.
         */
        ShipmentMaterialsCoverage: {
            materials_count: number;
            cost_kopecks: number;
            priced_count: number;
            unpriced_count: number;
            sold_products_count: number;
            exploded_products_count: number;
            without_plan_count: number;
            revenue_kopecks: number;
            documents_count: number;
            /** Format: decimal */
            cost_share_of_revenue: string | null;
        };
        /**
         * @description Итог под таблицей — про то, что в ней видно, с учётом поиска.
         *
         *     Обязан сходиться со сложением колонки: файл и экран открывают затем,
         *     чтобы складывать, и расхождение заметят раньше нас.
         */
        ShipmentMaterialsTotals: {
            materials_count: number;
            cost_kopecks: number;
            /** Format: decimal */
            cost_share: string | null;
            priced_count: number;
            unpriced_count: number;
        };
        ShipmentProductDetail: {
            channels: components["schemas"]["ChannelShare"][];
            documents: components["schemas"]["ProductDocument"][];
            stock: components["schemas"]["Stock"] | null;
        };
        ShipmentProductRow: {
            product_id: number;
            name: string;
            article: string;
            code: string;
            uom: string;
            /** Format: decimal */
            quantity: string;
            /** Format: decimal */
            free_quantity: string;
            revenue_kopecks: number;
            documents_count: number;
            /** Format: decimal */
            avg_price_kopecks: string | null;
            /** Format: decimal */
            avg_price_paid_kopecks: string | null;
            /** Format: decimal */
            revenue_share: string | null;
        };
        ShipmentProducts: {
            /** Format: date-time */
            synced_at: string | null;
            count: number;
            totals: components["schemas"]["ShipmentProductsTotals"];
            results: components["schemas"]["ShipmentProductRow"][];
            channels: components["schemas"]["SalesChannel"][];
        };
        ShipmentProductsTotals: {
            /** Format: decimal */
            quantity: string;
            /** Format: decimal */
            free_quantity: string;
            revenue_kopecks: number;
            documents_count: number;
            products_count: number;
        };
        /**
         * @description Что лежит на складе сейчас — одинаково для товара и для материала.
         *
         *     Один сериализатор, а не два одинаковых: из схемы генерируются типы
         *     фронтенда, и два близнеца дают два типа, под которые пишутся два
         *     компонента. Так и вышло — блок «Склад» разошёлся между страницами
         *     и на одной из них перестал отличать сбой связи от «остатка нет».
         */
        Stock: {
            /** Format: decimal */
            quantity: string;
            /** Format: decimal */
            reserved: string;
            /** Format: decimal */
            available: string;
            stock_days: number | null;
        };
        SyncRun: {
            status: string;
            status_label: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at: string | null;
            /** Format: double */
            duration_seconds: number | null;
            request_count: number;
            error: string;
        };
        SyncStatus: {
            running: boolean;
            /** Format: date-time */
            started_at: string | null;
        };
        /**
         * @description Проданное, чего техкарта не описывает: услуги и покупные товары.
         *
         *     Отдельным списком, а не строкой в таблице: доставка не сырьё, и в сумму
         *     материалов она не входит. Спрятать её тоже нельзя — тогда «сырья на
         *     399 686 ₽» читалось бы как расход по всей выручке.
         */
        WithoutPlanRow: {
            product_id: number;
            name: string;
            article: string;
            code: string;
            uom: string;
            is_service: boolean;
            /** Format: decimal */
            quantity: string;
            revenue_kopecks: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Csrf"];
                };
            };
        };
    };
    api_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    api_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    shipment_materials_list: {
        parameters: {
            query?: {
                channel_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-cost` - -cost
                 *     * `-name` - -name
                 *     * `-products` - -products
                 *     * `-quantity` - -quantity
                 *     * `-share` - -share
                 *     * `cost` - cost
                 *     * `name` - name
                 *     * `products` - products
                 *     * `quantity` - quantity
                 *     * `share` - share
                 */
                ordering?: "-cost" | "-name" | "-products" | "-quantity" | "-share" | "cost" | "name" | "products" | "quantity" | "share";
                page?: number;
                page_size?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentMaterials"];
                };
            };
        };
    };
    shipment_material_detail: {
        parameters: {
            query?: {
                channel_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-cost` - -cost
                 *     * `-name` - -name
                 *     * `-products` - -products
                 *     * `-quantity` - -quantity
                 *     * `-share` - -share
                 *     * `cost` - cost
                 *     * `name` - name
                 *     * `products` - products
                 *     * `quantity` - quantity
                 *     * `share` - share
                 */
                ordering?: "-cost" | "-name" | "-products" | "-quantity" | "-share" | "cost" | "name" | "products" | "quantity" | "share";
                page?: number;
                page_size?: number;
                search?: string;
            };
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentMaterialDetail"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    shipment_materials_xlsx: {
        parameters: {
            query?: {
                channel_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-cost` - -cost
                 *     * `-name` - -name
                 *     * `-products` - -products
                 *     * `-quantity` - -quantity
                 *     * `-share` - -share
                 *     * `cost` - cost
                 *     * `name` - name
                 *     * `products` - products
                 *     * `quantity` - quantity
                 *     * `share` - share
                 */
                ordering?: "-cost" | "-name" | "-products" | "-quantity" | "-share" | "cost" | "name" | "products" | "quantity" | "share";
                page?: number;
                page_size?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    shipment_products_list: {
        parameters: {
            query?: {
                channel_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-avg_price` - -avg_price
                 *     * `-free` - -free
                 *     * `-name` - -name
                 *     * `-quantity` - -quantity
                 *     * `-revenue` - -revenue
                 *     * `-share` - -share
                 *     * `avg_price` - avg_price
                 *     * `free` - free
                 *     * `name` - name
                 *     * `quantity` - quantity
                 *     * `revenue` - revenue
                 *     * `share` - share
                 */
                ordering?: "-avg_price" | "-free" | "-name" | "-quantity" | "-revenue" | "-share" | "avg_price" | "free" | "name" | "quantity" | "revenue" | "share";
                page?: number;
                page_size?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentProducts"];
                };
            };
        };
    };
    shipment_product_detail: {
        parameters: {
            query?: {
                channel_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-avg_price` - -avg_price
                 *     * `-free` - -free
                 *     * `-name` - -name
                 *     * `-quantity` - -quantity
                 *     * `-revenue` - -revenue
                 *     * `-share` - -share
                 *     * `avg_price` - avg_price
                 *     * `free` - free
                 *     * `name` - name
                 *     * `quantity` - quantity
                 *     * `revenue` - revenue
                 *     * `share` - share
                 */
                ordering?: "-avg_price" | "-free" | "-name" | "-quantity" | "-revenue" | "-share" | "avg_price" | "free" | "name" | "quantity" | "revenue" | "share";
                page?: number;
                page_size?: number;
                search?: string;
            };
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentProductDetail"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    shipment_products_xlsx: {
        parameters: {
            query?: {
                channel_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-avg_price` - -avg_price
                 *     * `-free` - -free
                 *     * `-name` - -name
                 *     * `-quantity` - -quantity
                 *     * `-revenue` - -revenue
                 *     * `-share` - -share
                 *     * `avg_price` - avg_price
                 *     * `free` - free
                 *     * `name` - name
                 *     * `quantity` - quantity
                 *     * `revenue` - revenue
                 *     * `share` - share
                 */
                ordering?: "-avg_price" | "-free" | "-name" | "-quantity" | "-revenue" | "-share" | "avg_price" | "free" | "name" | "quantity" | "revenue" | "share";
                page?: number;
                page_size?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    sync_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRun"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refused"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refused"];
                };
            };
        };
    };
    sync_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
        };
    };
    healthz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
