/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Выдать CSRF-куку перед формой входа.
         *
         *     Фронтенд — статика, отданная прокси, шаблонов Django он не рендерит,
         *     поэтому получить токен из скрытого поля формы неоткуда.
         */
        get: operations["api_auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/materials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Материалы в отгрузках
         * @description Сколько сырья ушло вместе с проданной продукцией. Проданное разворачивается по техкартам до того, что закупают.
         */
        get: operations["shipment_materials_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/materials/{material_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Материал в отгрузках — откуда взялось число
         * @description Из каких изделий материал пришёл и какими путями по техкартам. Фильтры те же, что у таблицы: слагаемые обязаны сходиться с числом своей строки.
         */
        get: operations["shipment_material_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/materials/xlsx/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Материалы в отгрузках — выгрузка в Excel
         * @description Та же выборка, что на экране, целиком. Вторым листом — проданное без техкарты: в сумму сырья оно не входит.
         */
        get: operations["shipment_materials_xlsx"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Товары в отгрузках
         * @description Что и сколько продано за период, свёрнутое по товару.
         */
        get: operations["shipment_products_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/products/{product_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Товар в отгрузках — детали строки
         * @description Разбивка по каналам, последние отгрузки и остаток. Фильтры те же, что у таблицы: детали обязаны сходиться с числами своей строки.
         */
        get: operations["shipment_product_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/products/xlsx/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Товары в отгрузках — выгрузка в Excel
         * @description Та же выборка, что на экране, но целиком: все страницы, а не видимая.
         */
        get: operations["shipment_products_xlsx"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Поставщики
         * @description Кто, на какие суммы и как часто поставляет: приёмки, наименования, регулярность поставок и срок от заказа до прихода товара.
         */
        get: operations["suppliers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/xlsx/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Поставщики — выгрузка в Excel
         * @description Та же выборка, что на экране, целиком. Вторым листом — каждая поставка отдельной строкой.
         */
        get: operations["suppliers_xlsx"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supplies/materials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Материалы в приёмках
         * @description Что и почём закупали за период: количества, суммы, средняя цена, последняя цена и её изменение к предыдущей закупке.
         */
        get: operations["supply_materials_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supplies/materials/{material_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Материал в приёмках — откуда взялось число
         * @description История закупок и сравнение поставщиков. Фильтры те же, что у таблицы: слагаемые обязаны сходиться с числом своей строки.
         */
        get: operations["supply_material_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supplies/materials/xlsx/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Материалы в приёмках — выгрузка в Excel
         * @description Та же выборка, что на экране, целиком. Вторым листом — каждая закупка отдельной строкой.
         */
        get: operations["supply_materials_xlsx"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обновить данные из МойСклада
         * @description Единственное место, где запрос человека доходит до МойСклада. Ограничено паузой между запусками и блокировкой: корзина лимита общая с ботом, который проверяет учёт круглосуточно.
         */
        post: operations["sync_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Идёт ли синхронизация
         * @description Состояние живёт на сервере, а не в памяти вкладки: иначе перезагрузка стирает его у запустившего, а остальные не видят вовсе.
         */
        get: operations["sync_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Контрагент с количеством: и покупатель, и получатель бесплатного.
         *
         *     Один тип на оба блока — поля совпадают до буквы, а два близнеца в схеме
         *     дали бы фронтенду два типа, под которые пишутся два компонента.
         */
        AgentShare: {
            agent_id: number;
            name: string;
            /** Format: decimal */
            quantity: string;
            revenue_kopecks: number;
            documents_count: number;
            notes?: string[];
        };
        /** @description Доля канала в продажах товара. Основа полос в раскрытии строки. */
        ChannelShare: {
            id: number | null;
            name: string;
            /** Format: decimal */
            quantity: string;
            revenue_kopecks: number;
        };
        Csrf: {
            csrfToken: string;
        };
        Detail: {
            detail: string;
        };
        /**
         * @description Значение справочника в выпадающем списке фильтров.
         *
         *     Один тип на канал продаж и на поставщика: в списке они устроены
         *     одинаково — идентификатор и подпись, — а два одинаковых типа в схеме
         *     дали бы фронтенду два компонента вместо одного поля фильтра.
         */
        FilterOption: {
            id: number;
            name: string;
        };
        Health: {
            status: string;
            database: string;
        };
        /**
         * @description Медиана в днях вместе с тем, из чего она получена.
         *
         *     Один тип на регулярность и на срок поставки: поля у них совпадают
         *     до буквы, и два близнеца в схеме дали бы фронтенду два типа, под которые
         *     пишутся два компонента. Так уже расходился блок «Склад».
         *
         *     Названия полей нейтральны к смыслу (`days`, а не `interval_days`)
         *     именно поэтому: подпись даёт колонка, а не контракт.
         */
        LeadTime: {
            /** Format: decimal */
            days: string | null;
            measurements: number;
            min_days: number | null;
            max_days: number | null;
            /** Format: decimal */
            average_days: string | null;
            unlinked: number;
        };
        Login: {
            username: string;
            password: string;
        };
        /**
         * @description На сколько хватит остатка при нынешнем расходе.
         *
         *     Один тип на два раздела: «Материалы в отгрузках» отвечают им на «надолго
         *     ли хватит», «Материалы в приёмках» — на «пора ли закупать». Вопрос разный,
         *     число одно, и разойтись оно не имеет права.
         *
         *     Первая половина порога закупки (`PRD.md` §5.9): `minimumBalance` пуст
         *     у всех 314 позиций, а расход за период против свободного остатка
         *     берётся из фактов учёта.
         *
         *     **Это не прогноз**, и подсказка на экране обязана это сказать: средний
         *     расход выбранного периода, а не тренд. Меняешь период — меняется число.
         */
        MaterialCoverage: {
            /** Format: decimal */
            quantity: string;
            /** Format: decimal */
            per_day: string;
            days_of_period: number;
            days_left: number | null;
            level: string;
        };
        MaterialDistribution: {
            top: components["schemas"]["MaterialShare"][];
            rest: components["schemas"]["MaterialShareRest"] | null;
        };
        /**
         * @description Шапка разбора строки: чем именно является материал.
         *
         *     Один сериализатор на оба раздела. Поля у них совпадали до буквы, и схема
         *     из-за двойника выдавала предупреждение «два компонента с одним именем
         *     и разными телами» — то есть фронтенд получил бы неверные типы, ничего
         *     об этом не узнав.
         */
        MaterialHead: {
            id: number;
            name: string;
            article: string;
            code: string;
            uom: string;
        };
        /**
         * @description Один путь по техкартам и то, сколько материала пришло именно им.
         *
         *     Количество обязательно: без него путь говорит «через замес и через
         *     розлив», но не отвечает, чего сколько, — а объяснение, которое не
         *     складывается обратно в объясняемое число, объяснением не является.
         */
        MaterialPath: {
            chain: string[];
            /** Format: decimal */
            quantity: string;
        };
        /**
         * @description Откуда взялась цена: документ, дата, поставщик.
         *
         *     Число, посчитанное по цене, обязано назвать её источник. Иначе колонка
         *     «Стоимость» остаётся суммой, за которую никто не отвечает.
         */
        MaterialPrice: {
            /** Format: decimal */
            price_kopecks: string;
            /** Format: date-time */
            moment: string;
            document_number: string;
            supplier: string;
        };
        /**
         * @description Норма расхода: сколько материала уходит на одно изделие.
         *
         *     Группой, а не по изделию: у 121 материала из 161 норма одна на все,
         *     и шестнадцать одинаковых строк не сообщают ничего сверх одной. У 40
         *     норма различается — у диметикона 200 г против 20 г, разница в десять
         *     раз, и увидеть её больше негде.
         */
        MaterialRate: {
            /** Format: decimal */
            rate: string;
            products_count: number;
            examples: string[];
        };
        /**
         * @description Свёрнутый хвост списка источников.
         *
         *     Без него показанные слагаемые не складывались бы в число, которое панель
         *     объясняет: у воды пятьдесят девять изделий-источников, а видно двадцать.
         */
        MaterialRest: {
            products_count: number;
            /** Format: decimal */
            quantity: string;
        };
        /** @description Изделие и его доля в расходе материала. */
        MaterialShare: {
            product_id: number;
            name: string;
            /** Format: decimal */
            quantity: string;
            /** Format: decimal */
            share: string | null;
        };
        /**
         * @description Свёрнутый хвост распределения.
         *
         *     Без него показанные доли не складываются в сто процентов, а количества —
         *     в объясняемое число, и расхождение спишут на расчёт.
         */
        MaterialShareRest: {
            products_count: number;
            /** Format: decimal */
            quantity: string;
            /** Format: decimal */
            share: string | null;
        };
        /** @description Изделие, из-за продажи которого материал израсходован. */
        MaterialSource: {
            product_id: number;
            name: string;
            /** Format: decimal */
            sold_quantity: string;
            sold_uom: string;
            /** Format: decimal */
            quantity: string;
            paths: components["schemas"]["MaterialPath"][];
        };
        /** @description Страница в меню. Префиксы API наружу не отдаются — это деталь защиты. */
        Page: {
            key: string;
            label: string;
            group: string;
            route: string;
        };
        /**
         * @description Точка ряда цен: когда и почём. Дата обязательна вместе с ценой.
         *
         *     Линия строится по времени, а не по номеру закупки: между 28.02 и 14.05
         *     два с половиной месяца, между 01.07 и 30.07 — один, и равные промежутки
         *     на экране соврали бы о том, как быстро материал дорожает.
         */
        PricePoint: {
            /** Format: date-time */
            moment: string;
            /** Format: decimal */
            price_kopecks: string;
        };
        Profile: {
            id: number;
            username: string;
            full_name: string;
            is_superuser: boolean;
            pages: components["schemas"]["Page"][];
        };
        /**
         * @description Одна закупка: документ целиком, а не строка в нём.
         *
         *     Цена средневзвешенная, если строк было несколько: диметилфталат пришёл
         *     одной приёмкой двумя партиями — 2000 г по 40 копеек и 3000 г по 45.
         *     Показать их двумя закупками значило бы нарисовать скачок цены,
         *     которого не было.
         */
        Purchase: {
            document_id: number;
            number: string;
            /** Format: date-time */
            moment: string;
            supplier: string;
            /** Format: decimal */
            quantity: string;
            amount_kopecks: number;
            /** Format: decimal */
            price_kopecks: string | null;
            is_free: boolean;
            /** Format: decimal */
            price_change: string | null;
        };
        /** @description Крупнейшие контрагенты плюс свёрнутый хвост. */
        Recipients: {
            agents: components["schemas"]["AgentShare"][];
            rest_agents_count: number;
            /** Format: decimal */
            rest_quantity: string;
            /** Format: decimal */
            quantity: string;
        };
        Refused: {
            detail: string;
            retry_after_seconds: number;
        };
        /**
         * @description Медиана в днях вместе с тем, из чего она получена.
         *
         *     Один тип на регулярность и на срок поставки: поля у них совпадают
         *     до буквы, и два близнеца в схеме дали бы фронтенду два типа, под которые
         *     пишутся два компонента. Так уже расходился блок «Склад».
         *
         *     Названия полей нейтральны к смыслу (`days`, а не `interval_days`)
         *     именно поэтому: подпись даёт колонка, а не контракт.
         */
        Regularity: {
            /** Format: decimal */
            days: string | null;
            measurements: number;
            min_days: number | null;
            max_days: number | null;
            /** Format: decimal */
            average_days: string | null;
        };
        ShipmentMaterialDetail: {
            material: components["schemas"]["MaterialHead"];
            /** Format: decimal */
            quantity: string;
            cost_kopecks: number | null;
            price: components["schemas"]["MaterialPrice"] | null;
            stock: components["schemas"]["Stock"] | null;
            coverage: components["schemas"]["MaterialCoverage"];
            rates: components["schemas"]["MaterialRate"][];
            distribution: components["schemas"]["MaterialDistribution"];
            sources_count: number;
            multi_path_count: number;
            sources: components["schemas"]["MaterialSource"][];
            rest: components["schemas"]["MaterialRest"] | null;
        };
        ShipmentMaterialRow: {
            material_id: number;
            name: string;
            article: string;
            code: string;
            uom: string;
            /** Format: decimal */
            quantity: string;
            products_count: number;
            /** Format: decimal */
            price_kopecks: string | null;
            /** Format: date-time */
            price_moment: string | null;
            cost_kopecks: number | null;
            /** Format: decimal */
            cost_share: string | null;
        };
        ShipmentMaterials: {
            /** Format: date-time */
            synced_at: string | null;
            count: number;
            totals: components["schemas"]["ShipmentMaterialsTotals"];
            coverage: components["schemas"]["ShipmentMaterialsCoverage"];
            results: components["schemas"]["ShipmentMaterialRow"][];
            without_plan: components["schemas"]["WithoutPlanRow"][];
            channels: components["schemas"]["FilterOption"][];
        };
        /**
         * @description Насколько полное число видит человек — про выборку отгрузок целиком.
         *
         *     Поиск сюда не входит намеренно: он сужает список материалов, а не то,
         *     что отгрузили. Возьми стоимость с учётом поиска, а выручку без —
         *     получится дробь, которая выглядит обычным процентом и врёт молча.
         */
        ShipmentMaterialsCoverage: {
            materials_count: number;
            cost_kopecks: number;
            priced_count: number;
            unpriced_count: number;
            sold_products_count: number;
            exploded_products_count: number;
            without_plan_count: number;
            revenue_kopecks: number;
            documents_count: number;
            /** Format: decimal */
            cost_share_of_revenue: string | null;
        };
        /**
         * @description Итог под таблицей — про то, что в ней видно, с учётом поиска.
         *
         *     Обязан сходиться со сложением колонки: файл и экран открывают затем,
         *     чтобы складывать, и расхождение заметят раньше нас.
         */
        ShipmentMaterialsTotals: {
            materials_count: number;
            cost_kopecks: number;
            /** Format: decimal */
            cost_share: string | null;
            priced_count: number;
            unpriced_count: number;
        };
        ShipmentProductDetail: {
            channels: components["schemas"]["ChannelShare"][];
            timeline: components["schemas"]["Timeline"];
            buyers: components["schemas"]["Recipients"] | null;
            free: components["schemas"]["Recipients"] | null;
            stock: components["schemas"]["Stock"] | null;
        };
        ShipmentProductRow: {
            product_id: number;
            name: string;
            article: string;
            code: string;
            uom: string;
            /** Format: decimal */
            quantity: string;
            /** Format: decimal */
            free_quantity: string;
            revenue_kopecks: number;
            documents_count: number;
            /** Format: decimal */
            avg_price_kopecks: string | null;
            /** Format: decimal */
            avg_price_paid_kopecks: string | null;
            /** Format: decimal */
            revenue_share: string | null;
        };
        ShipmentProducts: {
            /** Format: date-time */
            synced_at: string | null;
            count: number;
            totals: components["schemas"]["ShipmentProductsTotals"];
            results: components["schemas"]["ShipmentProductRow"][];
            channels: components["schemas"]["FilterOption"][];
        };
        ShipmentProductsTotals: {
            /** Format: decimal */
            quantity: string;
            /** Format: decimal */
            free_quantity: string;
            revenue_kopecks: number;
            documents_count: number;
            products_count: number;
            /** Format: decimal */
            revenue_share: string | null;
        };
        /**
         * @description Что лежит на складе сейчас — одинаково для товара и для материала.
         *
         *     Один сериализатор, а не два одинаковых: из схемы генерируются типы
         *     фронтенда, и два близнеца дают два типа, под которые пишутся два
         *     компонента. Так и вышло — блок «Склад» разошёлся между страницами
         *     и на одной из них перестал отличать сбой связи от «остатка нет».
         */
        Stock: {
            /** Format: decimal */
            quantity: string;
            /** Format: decimal */
            reserved: string;
            /** Format: decimal */
            available: string;
            stock_days: number | null;
        };
        SupplierMaterial: {
            name: string;
            amount_kopecks: number;
            /** Format: decimal */
            share: string | null;
        };
        /**
         * @description Что именно берём у поставщика: крупнейшие плюс свёрнутый хвост.
         *
         *     По суммам, а не по количествам: у материалов разные единицы — граммы
         *     против штук, — и сложить их нельзя. Деньги единственное, что у них общее.
         */
        SupplierMaterials: {
            items: components["schemas"]["SupplierMaterial"][];
            rest_count: number;
            rest_amount_kopecks: number;
        };
        /**
         * @description Что и почём брали у одного поставщика — строка сравнения.
         *
         *     `above_best` считается от самой низкой **последней** цены среди
         *     поставщиков. Не от крайних цен вообще: у «Крышки флип-топ» разброс между
         *     первой и последней ценой одного «Лемуна» — 73%, и назвать это разницей
         *     между поставщиками значило бы предложить уйти от него к нему же.
         */
        SupplierPrice: {
            supplier_id: number;
            name: string;
            supplies_count: number;
            /** Format: decimal */
            quantity: string;
            amount_kopecks: number;
            /** Format: decimal */
            avg_price_kopecks: string | null;
            /** Format: decimal */
            last_price_kopecks: string | null;
            /** Format: date-time */
            last_moment: string | null;
            /** Format: decimal */
            above_best: string | null;
        };
        SupplierRow: {
            supplier_id: number;
            name: string;
            supplies_count: number;
            delivery_days: number;
            amount_kopecks: number;
            /** Format: decimal */
            amount_share: string | null;
            /** Format: date-time */
            first_moment: string;
            /** Format: date-time */
            last_moment: string;
            materials_count: number;
            positions_count: number;
            free_positions_count: number;
            regularity: components["schemas"]["Regularity"];
            lead_time: components["schemas"]["LeadTime"];
            materials: components["schemas"]["SupplierMaterials"];
        };
        Suppliers: {
            count: number;
            /** Format: date-time */
            synced_at: string | null;
            totals: components["schemas"]["SuppliersTotals"];
            coverage: components["schemas"]["SuppliersCoverage"];
            results: components["schemas"]["SupplierRow"][];
        };
        /** @description Сводка — про выборку приёмок целиком. Поиск её не трогает. */
        SuppliersCoverage: {
            suppliers_count: number;
            supplies_count: number;
            amount_kopecks: number;
            positions_count: number;
            materials_count: number;
            free_positions_count: number;
            with_regularity_count: number;
            with_lead_time_count: number;
            unlinked_supplies_count: number;
        };
        /** @description Итог под таблицей — про то, что в ней видно, с учётом поиска. */
        SuppliersTotals: {
            suppliers_count: number;
            supplies_count: number;
            amount_kopecks: number;
            /** Format: decimal */
            amount_share: string | null;
            materials_count: number;
        };
        SupplyMaterialDetail: {
            material: components["schemas"]["MaterialHead"];
            /** Format: decimal */
            quantity: string;
            /** Format: decimal */
            free_quantity: string;
            /** Format: decimal */
            paid_quantity: string;
            amount_kopecks: number;
            /** Format: decimal */
            avg_price_kopecks: string | null;
            /** Format: decimal */
            price_change: string | null;
            history: components["schemas"]["Purchase"][];
            suppliers: components["schemas"]["SupplierPrice"][];
            stock: components["schemas"]["Stock"] | null;
            coverage: components["schemas"]["MaterialCoverage"];
        };
        SupplyMaterialRow: {
            material_id: number;
            name: string;
            article: string;
            code: string;
            uom: string;
            mixed_uom: boolean;
            /** Format: decimal */
            quantity: string;
            /** Format: decimal */
            free_quantity: string;
            /** Format: decimal */
            paid_quantity: string;
            amount_kopecks: number;
            /** Format: decimal */
            amount_share: string | null;
            /** Format: decimal */
            avg_price_kopecks: string | null;
            /** Format: decimal */
            last_price_kopecks: string | null;
            /** Format: date-time */
            last_moment: string | null;
            last_document_number: string | null;
            last_supplier: string | null;
            /** Format: decimal */
            previous_price_kopecks: string | null;
            /** Format: decimal */
            previous_quantity: string | null;
            /** Format: decimal */
            last_quantity: string | null;
            /** Format: decimal */
            price_change: string | null;
            prices: components["schemas"]["PricePoint"][];
            supplies_count: number;
            suppliers_count: number;
        };
        SupplyMaterials: {
            /** Format: date-time */
            synced_at: string | null;
            count: number;
            totals: components["schemas"]["SupplyMaterialsTotals"];
            coverage: components["schemas"]["SupplyMaterialsCoverage"];
            results: components["schemas"]["SupplyMaterialRow"][];
            suppliers: components["schemas"]["FilterOption"][];
        };
        /**
         * @description Насколько полное число видит человек — про выборку приёмок целиком.
         *
         *     Поиск сюда не входит намеренно: он сужает список материалов, а не то,
         *     что закупили.
         */
        SupplyMaterialsCoverage: {
            materials_count: number;
            amount_kopecks: number;
            documents_count: number;
            suppliers_count: number;
            positions_count: number;
            free_positions_count: number;
            priced_count: number;
            unpriced_count: number;
            with_history_count: number;
            multi_supplier_count: number;
        };
        /**
         * @description Итог под таблицей — про то, что в ней видно, с учётом поиска.
         *
         *     Обязан сходиться со сложением колонки: файл и экран открывают затем,
         *     чтобы складывать, и расхождение заметят раньше нас.
         */
        SupplyMaterialsTotals: {
            materials_count: number;
            amount_kopecks: number;
            /** Format: decimal */
            amount_share: string | null;
            priced_count: number;
            unpriced_count: number;
            documents_count: number;
            suppliers_count: number;
        };
        SyncRun: {
            status: string;
            status_label: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at: string | null;
            /** Format: double */
            duration_seconds: number | null;
            request_count: number;
            error: string;
        };
        SyncStatus: {
            running: boolean;
            /** Format: date-time */
            started_at: string | null;
        };
        /**
         * @description Продажи во времени. Заменило журнал последних отгрузок.
         *
         *     Шаг подбирается под период на сервере и приходит подписью: два места,
         *     решающие это по-своему, разъедутся, а человек обязан видеть, в чём мерят,
         *     иначе смена шага читается как смена данных.
         */
        Timeline: {
            step: string;
            step_label: string;
            points: components["schemas"]["TimelinePoint"][];
        };
        /** @description Один столбик: начало промежутка и что в него попало. */
        TimelinePoint: {
            /** Format: date */
            start: string;
            /** Format: date */
            end: string;
            /** Format: decimal */
            quantity: string;
            revenue_kopecks: number;
        };
        /**
         * @description Проданное, чего техкарта не описывает: услуги и покупные товары.
         *
         *     Отдельным списком, а не строкой в таблице: доставка не сырьё, и в сумму
         *     материалов она не входит. Спрятать её тоже нельзя — тогда «сырья на
         *     399 686 ₽» читалось бы как расход по всей выручке.
         */
        WithoutPlanRow: {
            product_id: number;
            name: string;
            article: string;
            code: string;
            uom: string;
            is_service: boolean;
            /** Format: decimal */
            quantity: string;
            revenue_kopecks: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Csrf"];
                };
            };
        };
    };
    api_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    api_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    shipment_materials_list: {
        parameters: {
            query?: {
                channel_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-cost` - -cost
                 *     * `-name` - -name
                 *     * `-products` - -products
                 *     * `-quantity` - -quantity
                 *     * `-share` - -share
                 *     * `cost` - cost
                 *     * `name` - name
                 *     * `products` - products
                 *     * `quantity` - quantity
                 *     * `share` - share
                 */
                ordering?: "-cost" | "-name" | "-products" | "-quantity" | "-share" | "cost" | "name" | "products" | "quantity" | "share";
                page?: number;
                page_size?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentMaterials"];
                };
            };
        };
    };
    shipment_material_detail: {
        parameters: {
            query?: {
                channel_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-cost` - -cost
                 *     * `-name` - -name
                 *     * `-products` - -products
                 *     * `-quantity` - -quantity
                 *     * `-share` - -share
                 *     * `cost` - cost
                 *     * `name` - name
                 *     * `products` - products
                 *     * `quantity` - quantity
                 *     * `share` - share
                 */
                ordering?: "-cost" | "-name" | "-products" | "-quantity" | "-share" | "cost" | "name" | "products" | "quantity" | "share";
                page?: number;
                page_size?: number;
                search?: string;
            };
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentMaterialDetail"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    shipment_materials_xlsx: {
        parameters: {
            query?: {
                channel_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-cost` - -cost
                 *     * `-name` - -name
                 *     * `-products` - -products
                 *     * `-quantity` - -quantity
                 *     * `-share` - -share
                 *     * `cost` - cost
                 *     * `name` - name
                 *     * `products` - products
                 *     * `quantity` - quantity
                 *     * `share` - share
                 */
                ordering?: "-cost" | "-name" | "-products" | "-quantity" | "-share" | "cost" | "name" | "products" | "quantity" | "share";
                page?: number;
                page_size?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    shipment_products_list: {
        parameters: {
            query?: {
                channel_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-avg_price` - -avg_price
                 *     * `-free` - -free
                 *     * `-name` - -name
                 *     * `-quantity` - -quantity
                 *     * `-revenue` - -revenue
                 *     * `-share` - -share
                 *     * `avg_price` - avg_price
                 *     * `free` - free
                 *     * `name` - name
                 *     * `quantity` - quantity
                 *     * `revenue` - revenue
                 *     * `share` - share
                 */
                ordering?: "-avg_price" | "-free" | "-name" | "-quantity" | "-revenue" | "-share" | "avg_price" | "free" | "name" | "quantity" | "revenue" | "share";
                page?: number;
                page_size?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentProducts"];
                };
            };
        };
    };
    shipment_product_detail: {
        parameters: {
            query?: {
                channel_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-avg_price` - -avg_price
                 *     * `-free` - -free
                 *     * `-name` - -name
                 *     * `-quantity` - -quantity
                 *     * `-revenue` - -revenue
                 *     * `-share` - -share
                 *     * `avg_price` - avg_price
                 *     * `free` - free
                 *     * `name` - name
                 *     * `quantity` - quantity
                 *     * `revenue` - revenue
                 *     * `share` - share
                 */
                ordering?: "-avg_price" | "-free" | "-name" | "-quantity" | "-revenue" | "-share" | "avg_price" | "free" | "name" | "quantity" | "revenue" | "share";
                page?: number;
                page_size?: number;
                search?: string;
            };
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentProductDetail"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    shipment_products_xlsx: {
        parameters: {
            query?: {
                channel_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-avg_price` - -avg_price
                 *     * `-free` - -free
                 *     * `-name` - -name
                 *     * `-quantity` - -quantity
                 *     * `-revenue` - -revenue
                 *     * `-share` - -share
                 *     * `avg_price` - avg_price
                 *     * `free` - free
                 *     * `name` - name
                 *     * `quantity` - quantity
                 *     * `revenue` - revenue
                 *     * `share` - share
                 */
                ordering?: "-avg_price" | "-free" | "-name" | "-quantity" | "-revenue" | "-share" | "avg_price" | "free" | "name" | "quantity" | "revenue" | "share";
                page?: number;
                page_size?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    suppliers_list: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-amount` - -amount
                 *     * `-last` - -last
                 *     * `-lead_time` - -lead_time
                 *     * `-materials` - -materials
                 *     * `-name` - -name
                 *     * `-regularity` - -regularity
                 *     * `-supplies` - -supplies
                 *     * `amount` - amount
                 *     * `last` - last
                 *     * `lead_time` - lead_time
                 *     * `materials` - materials
                 *     * `name` - name
                 *     * `regularity` - regularity
                 *     * `supplies` - supplies
                 */
                ordering?: "-amount" | "-last" | "-lead_time" | "-materials" | "-name" | "-regularity" | "-supplies" | "amount" | "last" | "lead_time" | "materials" | "name" | "regularity" | "supplies";
                page?: number;
                page_size?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suppliers"];
                };
            };
        };
    };
    suppliers_xlsx: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-amount` - -amount
                 *     * `-last` - -last
                 *     * `-lead_time` - -lead_time
                 *     * `-materials` - -materials
                 *     * `-name` - -name
                 *     * `-regularity` - -regularity
                 *     * `-supplies` - -supplies
                 *     * `amount` - amount
                 *     * `last` - last
                 *     * `lead_time` - lead_time
                 *     * `materials` - materials
                 *     * `name` - name
                 *     * `regularity` - regularity
                 *     * `supplies` - supplies
                 */
                ordering?: "-amount" | "-last" | "-lead_time" | "-materials" | "-name" | "-regularity" | "-supplies" | "amount" | "last" | "lead_time" | "materials" | "name" | "regularity" | "supplies";
                page?: number;
                page_size?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    supply_materials_list: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-amount` - -amount
                 *     * `-avg_price` - -avg_price
                 *     * `-change` - -change
                 *     * `-last_price` - -last_price
                 *     * `-name` - -name
                 *     * `-quantity` - -quantity
                 *     * `-suppliers` - -suppliers
                 *     * `-supplies` - -supplies
                 *     * `amount` - amount
                 *     * `avg_price` - avg_price
                 *     * `change` - change
                 *     * `last_price` - last_price
                 *     * `name` - name
                 *     * `quantity` - quantity
                 *     * `suppliers` - suppliers
                 *     * `supplies` - supplies
                 */
                ordering?: "-amount" | "-avg_price" | "-change" | "-last_price" | "-name" | "-quantity" | "-suppliers" | "-supplies" | "amount" | "avg_price" | "change" | "last_price" | "name" | "quantity" | "suppliers" | "supplies";
                page?: number;
                page_size?: number;
                search?: string;
                supplier_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplyMaterials"];
                };
            };
        };
    };
    supply_material_detail: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-amount` - -amount
                 *     * `-avg_price` - -avg_price
                 *     * `-change` - -change
                 *     * `-last_price` - -last_price
                 *     * `-name` - -name
                 *     * `-quantity` - -quantity
                 *     * `-suppliers` - -suppliers
                 *     * `-supplies` - -supplies
                 *     * `amount` - amount
                 *     * `avg_price` - avg_price
                 *     * `change` - change
                 *     * `last_price` - last_price
                 *     * `name` - name
                 *     * `quantity` - quantity
                 *     * `suppliers` - suppliers
                 *     * `supplies` - supplies
                 */
                ordering?: "-amount" | "-avg_price" | "-change" | "-last_price" | "-name" | "-quantity" | "-suppliers" | "-supplies" | "amount" | "avg_price" | "change" | "last_price" | "name" | "quantity" | "suppliers" | "supplies";
                page?: number;
                page_size?: number;
                search?: string;
                supplier_id?: number | null;
            };
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplyMaterialDetail"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    supply_materials_xlsx: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                /**
                 * @description * `-amount` - -amount
                 *     * `-avg_price` - -avg_price
                 *     * `-change` - -change
                 *     * `-last_price` - -last_price
                 *     * `-name` - -name
                 *     * `-quantity` - -quantity
                 *     * `-suppliers` - -suppliers
                 *     * `-supplies` - -supplies
                 *     * `amount` - amount
                 *     * `avg_price` - avg_price
                 *     * `change` - change
                 *     * `last_price` - last_price
                 *     * `name` - name
                 *     * `quantity` - quantity
                 *     * `suppliers` - suppliers
                 *     * `supplies` - supplies
                 */
                ordering?: "-amount" | "-avg_price" | "-change" | "-last_price" | "-name" | "-quantity" | "-suppliers" | "-supplies" | "amount" | "avg_price" | "change" | "last_price" | "name" | "quantity" | "suppliers" | "supplies";
                page?: number;
                page_size?: number;
                search?: string;
                supplier_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    sync_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRun"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refused"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refused"];
                };
            };
        };
    };
    sync_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
        };
    };
    healthz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
