# Generated by Django 5.2.17 on 2026-08-27 08:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('documents', 'Документы — ночью'), ('state', 'Состояние — каждые 10–15 минут')], max_length=16, verbose_name='Что синхронизируем')),
                ('status', models.CharField(choices=[('running', 'Идёт'), ('success', 'Успешно'), ('partial', 'Частично — часть сущностей не обновилась'), ('failed', 'Не удалось')], default='running', max_length=16, verbose_name='Итог')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начат')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Закончен')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='Запросов к API')),
                ('triggered_manually', models.BooleanField(default=False, verbose_name='Запущен кнопкой')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Прогон синхронизации',
                'verbose_name_plural': 'Прогоны синхронизации',
                'indexes': [models.Index(fields=['kind', '-started_at'], name='core_syncru_kind_5a148e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncEntityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=64, verbose_name='Сущность')),
                ('status', models.CharField(choices=[('running', 'Идёт'), ('success', 'Успешно'), ('partial', 'Частично — часть сущностей не обновилась'), ('failed', 'Не удалось')], max_length=16, verbose_name='Итог')),
                ('fetched', models.PositiveIntegerField(default=0, verbose_name='Получено из API')),
                ('created', models.PositiveIntegerField(default=0, verbose_name='Создано')),
                ('updated', models.PositiveIntegerField(default=0, verbose_name='Обновлено')),
                ('marked_deleted', models.PositiveIntegerField(default=0, verbose_name='Помечено удалёнными')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.syncrun')),
            ],
            options={
                'verbose_name': 'Результат по сущности',
                'verbose_name_plural': 'Результаты по сущностям',
                'constraints': [models.UniqueConstraint(fields=('run', 'entity'), name='unique_run_entity')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.UUIDField(db_index=True, unique=True, verbose_name='Идентификатор в МойСкладе')),
                ('ms_updated', models.DateTimeField(blank=True, null=True, verbose_name='Изменён в учёте')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Строка не удаляется физически: на неё могут ссылаться данные, введённые людьми.', null=True, verbose_name='Исчез из учёта')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено у нас')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Код')),
                ('folder', models.CharField(blank=True, max_length=255, verbose_name='Группа')),
                ('uom', models.CharField(blank=True, max_length=32, verbose_name='Единица измерения')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('buy_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Закупочная цена')),
                ('min_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='Неснижаемый остаток')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.syncrun', verbose_name='Последний раз видели в прогоне')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'indexes': [models.Index(fields=['name'], name='core_produc_name_be3252_idx'), models.Index(fields=['article'], name='core_produc_article_2e7f9d_idx')],
            },
        ),
    ]
