# Generated by Django 5.2.17 on 2026-08-27 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_syncrun_syncentityresult_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.UUIDField(db_index=True, unique=True, verbose_name='Идентификатор в МойСкладе')),
                ('ms_updated', models.DateTimeField(blank=True, null=True, verbose_name='Изменён в учёте')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Строка не удаляется физически: на неё могут ссылаться данные, введённые людьми.', null=True, verbose_name='Исчез из учёта')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено у нас')),
                ('name', models.CharField(max_length=32, verbose_name='Обозначение')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.syncrun', verbose_name='Последний раз видели в прогоне')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        # Поле было текстовым и у всех товаров пустым: код читал `uom.name`,
        # которого в ответе API нет — там только ссылка. Postgres не умеет
        # превращать '' в ссылку, поэтому сначала снимаем NOT NULL и чистим.
        migrations.RunSQL(
            sql=[
                "ALTER TABLE core_product ALTER COLUMN uom DROP NOT NULL",
                "UPDATE core_product SET uom = NULL WHERE uom = ''",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.uom', verbose_name='Единица измерения'),
        ),
    ]
