# Generated by Django 5.2.17 on 2026-08-27 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uom_alter_product_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.UUIDField(db_index=True, unique=True, verbose_name='Идентификатор в МойСкладе')),
                ('ms_updated', models.DateTimeField(blank=True, null=True, verbose_name='Изменён в учёте')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Строка не удаляется физически: на неё могут ссылаться данные, введённые людьми.', null=True, verbose_name='Исчез из учёта')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено у нас')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.syncrun', verbose_name='Последний раз видели в прогоне')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.UUIDField(db_index=True, unique=True, verbose_name='Идентификатор в МойСкладе')),
                ('ms_updated', models.DateTimeField(blank=True, null=True, verbose_name='Изменён в учёте')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Строка не удаляется физически: на неё могут ссылаться данные, введённые людьми.', null=True, verbose_name='Исчез из учёта')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено у нас')),
                ('kind', models.CharField(choices=[('demand', 'Отгрузка'), ('supply', 'Приёмка')], db_index=True, max_length=16, verbose_name='Вид')),
                ('number', models.CharField(max_length=64, verbose_name='Номер')),
                ('moment', models.DateTimeField(db_index=True, verbose_name='Дата документа')),
                ('total_kopecks', models.BigIntegerField(default=0, verbose_name='Сумма, копейки')),
                ('paid_kopecks', models.BigIntegerField(default=0, verbose_name='Оплачено, копейки')),
                ('vat_kopecks', models.BigIntegerField(default=0, verbose_name='НДС, копейки')),
                ('applicable', models.BooleanField(default=True, verbose_name='Проведён')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.counterparty', verbose_name='Контрагент')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.syncrun', verbose_name='Последний раз видели в прогоне')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='DocumentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Цена за единицу')),
                ('discount', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Скидка, %')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='core.product', verbose_name='Товар')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.uom', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Позиция документа',
                'verbose_name_plural': 'Позиции документов',
            },
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.UUIDField(db_index=True, unique=True, verbose_name='Идентификатор в МойСкладе')),
                ('ms_updated', models.DateTimeField(blank=True, null=True, verbose_name='Изменён в учёте')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Строка не удаляется физически: на неё могут ссылаться данные, введённые людьми.', null=True, verbose_name='Исчез из учёта')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено у нас')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(blank=True, max_length=64, verbose_name='Тип')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.syncrun', verbose_name='Последний раз видели в прогоне')),
            ],
            options={
                'verbose_name': 'Канал продаж',
                'verbose_name_plural': 'Каналы продаж',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='sales_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.saleschannel', verbose_name='Канал продаж'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['name'], name='core_counte_name_15f4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentposition',
            index=models.Index(fields=['document', 'product'], name='core_docume_documen_d2eeba_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['kind', '-moment'], name='core_docume_kind_7d7e79_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['kind', 'agent'], name='core_docume_kind_8f1704_idx'),
        ),
    ]
