# Generated by Django 5.2.17 on 2026-08-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_counterparty_document_documentposition_saleschannel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('product', 'Товар или материал'), ('service', 'Услуга')], default='product', max_length=16, verbose_name='Вид'),
        ),
    ]
