# Generated by Django 5.2.17 on 2026-08-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentposition',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buy_price',
        ),
        migrations.AddField(
            model_name='documentposition',
            name='price_kopecks',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Цена за единицу, копейки'),
        ),
        migrations.AddField(
            model_name='documentposition',
            name='total_kopecks',
            field=models.BigIntegerField(default=0, verbose_name='Сумма строки, копейки'),
        ),
        migrations.AddField(
            model_name='product',
            name='buy_price_kopecks',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Закупочная цена, копейки'),
        ),
        migrations.AlterField(
            model_name='documentposition',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Количество'),
        ),
    ]
