# Generated by Django 5.2.17 on 2026-08-27 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_documentposition_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.UUIDField(db_index=True, unique=True, verbose_name='Идентификатор в МойСкладе')),
                ('ms_updated', models.DateTimeField(blank=True, null=True, verbose_name='Изменён в учёте')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Строка не удаляется физически: на неё могут ссылаться данные, введённые людьми.', null=True, verbose_name='Исчез из учёта')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено у нас')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('folder', models.CharField(blank=True, max_length=255, verbose_name='Группа')),
                ('output_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=18, verbose_name='Объём выпуска')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.syncrun', verbose_name='Последний раз видели в прогоне')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produced_by', to='core.product', verbose_name='Что выпускается')),
            ],
            options={
                'verbose_name': 'Техкарта',
                'verbose_name_plural': 'Техкарты',
            },
        ),
        migrations.CreateModel(
            name='ProcessingPlanMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Количество')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.processingplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='core.product', verbose_name='Материал')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.uom', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Материал техкарты',
                'verbose_name_plural': 'Материалы техкарт',
            },
        ),
        migrations.AddIndex(
            model_name='processingplan',
            index=models.Index(fields=['product'], name='core_proces_product_a02f07_idx'),
        ),
        migrations.AddIndex(
            model_name='processingplanmaterial',
            index=models.Index(fields=['plan', 'product'], name='core_proces_plan_id_d2cf6d_idx'),
        ),
    ]
