# Generated by Django 5.2.17 on 2026-08-27 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_processingplan_processingplanmaterial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Всего')),
                ('reserved', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='В резерве')),
                ('in_transit', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Ожидается')),
                ('cost_kopecks', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Себестоимость единицы, копейки')),
                ('stock_days', models.IntegerField(blank=True, null=True, verbose_name='Дней без движения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
                'indexes': [models.Index(fields=['-stock_days'], name='core_stock_stock_d_ea666f_idx')],
            },
        ),
    ]
