# Generated by Django 5.2.17 on 2026-08-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingplan',
            name='folder',
            field=models.TextField(blank=True, verbose_name='Группа'),
        ),
    ]
