# Generated by Django 5.2.17 on 2026-08-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_processingplan_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='core.document', verbose_name='Заказ поставщику'),
        ),
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('demand', 'Отгрузка'), ('supply', 'Приёмка'), ('purchase_order', 'Заказ поставщику')], db_index=True, max_length=16, verbose_name='Вид'),
        ),
    ]
