# Generated by Django 5.2.17 on 2026-08-30 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_document_purchase_order_alter_document_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='core.document', verbose_name='Заказ покупателя'),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('demand', 'Отгрузка'), ('supply', 'Приёмка'), ('purchase_order', 'Заказ поставщику'), ('customer_order', 'Заказ покупателя')], db_index=True, max_length=16, verbose_name='Вид'),
        ),
    ]
