# Generated by Django 5.2.17 on 2026-09-02 08:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_document_customer_order_document_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritebackSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cost_prices', 'Себестоимость → тип цены в карточке товара')], max_length=32, unique=True, verbose_name='Вид записи')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включена')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Выключатель обратной записи',
                'verbose_name_plural': 'Выключатели обратной записи',
            },
        ),
        migrations.CreateModel(
            name='WritebackRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cost_prices', 'Себестоимость → тип цены в карточке товара')], max_length=32, verbose_name='Вид записи')),
                ('status', models.CharField(choices=[('running', 'Идёт'), ('success', 'Успешно'), ('partial', 'Частично — часть записей не прошла'), ('failed', 'Не удалось'), ('blocked', 'Отменён — выключатель выключен'), ('stopped', 'Остановлен предохранителем')], default='running', max_length=16, verbose_name='Итог')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начат')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Закончен')),
                ('dry_run', models.BooleanField(default=False, verbose_name='Пробный прогон')),
                ('triggered_manually', models.BooleanField(default=False, verbose_name='Запущен вручную')),
                ('considered', models.PositiveIntegerField(default=0, verbose_name='Рассмотрено')),
                ('changed', models.PositiveIntegerField(default=0, verbose_name='Изменено')),
                ('skipped', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('failed', models.PositiveIntegerField(default=0, verbose_name='Не удалось записать')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='Запросов к API')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Прогон обратной записи',
                'verbose_name_plural': 'Прогоны обратной записи',
                'indexes': [models.Index(fields=['kind', '-started_at'], name='core_writeb_kind_f4a54d_idx')],
            },
        ),
        migrations.CreateModel(
            name='WritebackChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_ms_id', models.UUIDField(verbose_name='Идентификатор в МойСкладе')),
                ('target_name', models.CharField(max_length=255, verbose_name='Что меняли')),
                ('field', models.CharField(max_length=64, verbose_name='Какое поле')),
                ('old_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Было')),
                ('new_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Стало')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка записи')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='core.writebackrun')),
            ],
            options={
                'verbose_name': 'Запись в учёт',
                'verbose_name_plural': 'Записи в учёт',
                'indexes': [models.Index(fields=['run'], name='core_writeb_run_id_9222f8_idx'), models.Index(fields=['target_ms_id'], name='core_writeb_target__9ba753_idx')],
            },
        ),
    ]
