# Generated by Django 5.2.17 on 2026-09-02 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_writebackswitch_writebackrun_writebackchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='deferral_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Отсрочка, дней'),
        ),
        migrations.AddField(
            model_name='document',
            name='deferral_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Индивидуальная отсрочка, дней'),
        ),
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('demand', 'Отгрузка'), ('supply', 'Приёмка'), ('purchase_order', 'Заказ поставщику'), ('customer_order', 'Заказ покупателя'), ('commission_report', 'Отчёт комиссионера')], db_index=True, max_length=24, verbose_name='Вид'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.UUIDField(db_index=True, unique=True, verbose_name='Идентификатор в МойСкладе')),
                ('ms_updated', models.DateTimeField(blank=True, null=True, verbose_name='Изменён в учёте')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Строка не удаляется физически: на неё могут ссылаться данные, введённые людьми.', null=True, verbose_name='Исчез из учёта')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено у нас')),
                ('name', models.CharField(max_length=255, verbose_name='Номер договора')),
                ('contract_type', models.CharField(choices=[('sales', 'Купли-продажи'), ('commission', 'Комиссии')], default='sales', max_length=16, verbose_name='Тип')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.counterparty', verbose_name='Контрагент')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.syncrun', verbose_name='Последний раз видели в прогоне')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.contract', verbose_name='Договор'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_type'], name='core_contra_contrac_c8b38d_idx'),
        ),
    ]
