# Generated by Django 5.2.17 on 2026-09-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_writeback_switches'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Группы'),
        ),
    ]
