# Generated by Django 5.2.17 on 2026-09-02 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_counterparty_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='День')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Продано')),
                ('revenue_kopecks', models.BigIntegerField(default=0, verbose_name='Выручка, копейки')),
                ('cost_kopecks', models.BigIntegerField(default=0, verbose_name='Себестоимость, копейки')),
                ('marketplace_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Продано через площадки')),
                ('marketplace_revenue_kopecks', models.BigIntegerField(default=0, verbose_name='Выручка через площадки, копейки')),
                ('marketplace_cost_kopecks', models.BigIntegerField(default=0, verbose_name='Себестоимость через площадки, копейки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_days', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Прибыльность за день',
                'verbose_name_plural': 'Прибыльность по дням',
                'indexes': [models.Index(fields=['product', '-date'], name='core_profit_product_da75a3_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'product'), name='profit_day_unique_product_per_day')],
            },
        ),
    ]
