# Generated by Django 5.2.17 on 2026-09-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profitday'),
    ]

    operations = [
        migrations.AddField(
            model_name='writebackrun',
            name='skipped_equal',
            field=models.PositiveIntegerField(default=0, verbose_name='Пропущено: уже совпадает'),
        ),
        migrations.AddField(
            model_name='writebackrun',
            name='skipped_unknown',
            field=models.PositiveIntegerField(default=0, verbose_name='Пропущено: значение неизвестно'),
        ),
    ]
