# Generated by Django 5.2.17 on 2026-09-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_writeback_skip_reasons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpageaccess',
            options={'verbose_name': 'Выданный доступ', 'verbose_name_plural': 'Кому что выдано'},
        ),
        migrations.AlterModelOptions(
            name='writebackchange',
            options={'verbose_name': 'Изменение в карточке товара', 'verbose_name_plural': 'Изменения в карточках товаров'},
        ),
        migrations.AlterModelOptions(
            name='writebackrun',
            options={'verbose_name': 'Запуск записи в МойСклад', 'verbose_name_plural': 'Журнал: записи в МойСклад'},
        ),
        migrations.AlterModelOptions(
            name='writebackswitch',
            options={'verbose_name': 'Что система пишет в МойСклад', 'verbose_name_plural': 'Что система пишет в МойСклад'},
        ),
    ]
