# Generated by Django 5.2.17 on 2026-09-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_userpageaccess_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=64, verbose_name='Должность'),
        ),
    ]
