# Generated by Django 5.2.17 on 2026-09-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpageaccess',
            options={'verbose_name': 'Выданный доступ', 'verbose_name_plural': 'Выданные доступы'},
        ),
    ]
