# Generated by Django 5.2.17 on 2026-09-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_userpageaccess_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writebackrun',
            options={'verbose_name': 'Запуск записи в МойСклад', 'verbose_name_plural': 'Журнал: что мы записали в МойСклад'},
        ),
        migrations.AlterModelOptions(
            name='writebackswitch',
            options={'verbose_name': 'Автоматическая запись в МойСклад', 'verbose_name_plural': 'Автоматические записи в МойСклад'},
        ),
    ]
