# Generated by Django 5.2.17 on 2026-09-03 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_writebackrun_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writebackrun',
            options={'verbose_name': 'Запуск проставления себестоимости', 'verbose_name_plural': 'Журнал: проставление себестоимости'},
        ),
        migrations.AlterModelOptions(
            name='writebackswitch',
            options={'verbose_name': 'Скрипт проставления себестоимости', 'verbose_name_plural': 'Скрипт проставления себестоимости'},
        ),
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начат')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Закончен')),
                ('status', models.CharField(choices=[('running', 'Идёт'), ('success', 'Готово'), ('failed', 'Не удалось')], default='running', max_length=16, verbose_name='Итог')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Файл архива')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Размер, байт')),
                ('verified', models.BooleanField(default=False, verbose_name='Проверен восстановлением')),
                ('pruned', models.JSONField(blank=True, default=list, verbose_name='Удалённые архивы')),
                ('kept', models.PositiveIntegerField(default=0, verbose_name='Осталось архивов')),
                ('dry_run', models.BooleanField(default=False, verbose_name='Пробный прогон')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Запуск бэкапа',
                'verbose_name_plural': 'Скрипт бэкапа',
                'indexes': [models.Index(fields=['-started_at'], name='core_backup_started_555d2c_idx')],
            },
        ),
    ]
