# Generated by Django 5.2.17 on 2026-09-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_writebackrun_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backuprun',
            options={'verbose_name': 'Запуск бэкапа', 'verbose_name_plural': 'Бэкапы базы'},
        ),
        migrations.AlterModelOptions(
            name='syncrun',
            options={'verbose_name': 'Прогон синхронизации', 'verbose_name_plural': 'Синхронизация с МойСкладом'},
        ),
        migrations.AlterModelOptions(
            name='writebackrun',
            options={'verbose_name': 'Запуск проставления себестоимости', 'verbose_name_plural': 'Проставление себестоимости'},
        ),
    ]
