# Generated by Django 5.2.17 on 2026-09-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_backuprun_options_alter_syncrun_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writebackswitch',
            options={'verbose_name': 'Скрипт', 'verbose_name_plural': 'Скрипты'},
        ),
        migrations.AlterField(
            model_name='writebackrun',
            name='kind',
            field=models.CharField(choices=[('cost_prices', 'Проставление себестоимости в карточки МойСклада')], max_length=32, verbose_name='Вид записи'),
        ),
        migrations.AlterField(
            model_name='writebackswitch',
            name='kind',
            field=models.CharField(choices=[('cost_prices', 'Проставление себестоимости в карточки МойСклада')], max_length=32, unique=True, verbose_name='Вид записи'),
        ),
    ]
