# Generated by Django 5.2.17 on 2026-09-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_writebackswitch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дней на складе'),
        ),
    ]
