# Generated by Django 5.2.17 on 2026-09-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_stock_stock_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sale_price_kopecks',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Цена продажи, копейки'),
        ),
    ]
