# Generated by Django 5.2.17 on 2026-09-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_seed_min_balance_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writebackrun',
            name='kind',
            field=models.CharField(choices=[('cost_prices', 'Проставление себестоимости в карточки МойСклада'), ('min_balance', 'Проставление неснижаемого остатка в карточки МойСклада')], max_length=32, verbose_name='Вид записи'),
        ),
        migrations.AlterField(
            model_name='writebackswitch',
            name='kind',
            field=models.CharField(choices=[('cost_prices', 'Проставление себестоимости в карточки МойСклада'), ('min_balance', 'Проставление неснижаемого остатка в карточки МойСклада')], max_length=32, unique=True, verbose_name='Вид записи'),
        ),
    ]
