# Generated by Django 5.2.17 on 2026-09-04 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_writebackrun_kind_alter_writebackswitch_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.UUIDField(db_index=True, unique=True, verbose_name='Идентификатор в МойСкладе')),
                ('ms_updated', models.DateTimeField(blank=True, null=True, verbose_name='Изменён в учёте')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Строка не удаляется физически: на неё могут ссылаться данные, введённые людьми.', null=True, verbose_name='Исчез из учёта')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено у нас')),
                ('number', models.CharField(max_length=64, verbose_name='Номер')),
                ('moment', models.DateTimeField(db_index=True, verbose_name='Дата документа')),
                ('total_kopecks', models.BigIntegerField(default=0, verbose_name='Сумма, копейки')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.syncrun', verbose_name='Последний раз видели в прогоне')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
            },
        ),
        migrations.CreateModel(
            name='InventoryPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Фактически')),
                ('calculated', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Числилось')),
                ('correction_amount', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Расхождение')),
                ('correction_sum_kopecks', models.BigIntegerField(default=0, verbose_name='Расхождение, копейки')),
                ('price_kopecks', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Цена за единицу, копейки')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_positions', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция инвентаризации',
                'verbose_name_plural': 'Позиции инвентаризаций',
            },
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['-moment'], name='core_invent_moment_49f8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryposition',
            index=models.Index(fields=['inventory', 'product'], name='core_invent_invento_6a263c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryposition',
            index=models.Index(fields=['product'], name='core_invent_product_504599_idx'),
        ),
    ]
