# Generated by Django 5.2.17 on 2026-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_inventory_inventoryposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Склад'),
        ),
    ]
