# Generated by Django 5.2.17 on 2026-09-05 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_inventory_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(db_index=True, max_length=255, verbose_name='Склад')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Остаток')),
                ('reserved', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='В резерве')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_stocks', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Остаток по складу',
                'verbose_name_plural': 'Остатки по складам',
                'indexes': [models.Index(fields=['store_name'], name='core_stores_store_n_d11dae_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'store_name'), name='unique_product_store')],
            },
        ),
    ]
